# Generated by Django 4.0.4 on 2022-05-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picasso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pin',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='pin',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='tag',
            new_name='location',
        ),
    ]
